### ISSUE TITLE
Revisión apuntamentos SQL DQL 17 de febreiro de 2020 ASIR

### ISSUE THREAD

**Issue by davidgchaves** [davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1#1]
Formato recomendado

```
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<url-revisión>) 🚀👾🤖👽

- A <nome-alumno-e-primeira-letra-do-apelido-revisado> co usuario <@usuario-de-github>.
- Por <nome-alumno-e-primeira-letra-do-apelido-que-revisa> co usuario <@usuario-de-github>.
```

**Comment by Neragorn** [comment]
Mi compañero no tiene los apuntes realizados.
Es mejor en mis apuntes en que son más breves, aunque no tan específicos.
Los míos son mejores en que están hechos.
Lamentablemente la nota es un 0 en mi compañero. En cuanto a mi nota, después de revisarlos hoy, al encontrar ciertos errores de texto no encontrados ayer en el último commit, pienso que merezco entre un 7 y un , un 9, dependiendo de la evaluación hecha por mi compañero en cuanto a cosas que haya o no encontrado y que yo no me haya dado cuenta.

**Comment by juliospau** [comment]
[ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/Eduramirez97/ApuntesMySql/issues/1) 

- A Eduardo R. co usuario @Eduramirez97.
- Por Julio S. co usuario @Jul10-S.

**Comment by nubevoladorakinto** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/juanseijo/sql-dql/issues/1#issue-566120365>) 🚀👾🤖👽

- A <Juan S> co usuario <@juanseijo>.
- Por <Ceo R> co usuario <@nubevoladorakinto>.

**Comment by patri30suarez** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/alexbs01/SQL/issues/1>) 🚀👾🤖👽

- A <Alex B> co usuario <@alexb01>.
- Por <Patricia S> co usuario <@patri30suarez>.

**Comment by Neragorn** [comment]
[ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/inhigovarela/inhigovarela/issues/1)
Revisión a @inhigovarela
Por @Neragorn

**Comment by anxocr8** [comment]
[ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/xRase123/Apuntes-SQL/issues/1>)

- A Javier Campos co usuario <@xRase123>

- Por Ángel Cerdeiro co usuario <@anxocr8>

**Comment by nekaneAmeijeiras** [comment]
Los apuntes no han sido entregados por mi compañero por lo que la nota es un 0.
Mi nota creo que podría estar entre un siete u ocho.

- A Alberto Beraza Aradas @AlbertoBerazaAradas
- Por Nekane Ameijeiras Rodríguez @NekaneAmeijeiras

**Comment by AdolfoGarcia10** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/TheRoXaS29/sql/issues/1) 🚀👾🤖👽 

Revisión a Diego V.     <@TheRoxaS29>
Revisado por               <@AdolfoGarcia10>

**Comment by adrimerino** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/Neragorn/SQL-Apuntes/issues/15#issue-566129493>) 🚀👾🤖👽

- A <Moisés B.> co usuario <@Neragorn>.
- Por <Adrián M.> co usuario <@adrimerino>.

**Comment by SoyIago** [comment]
👽🤖👾🚀 [ligazón á revisión apuntamentos SQL DQL 17 de febreiro de 2020](https://github.com/pmareque/Apuntes-BD/issues/1) 🚀👾🤖👽

- A Paloma M. co usuario @pmareque.
- Por Iago C. co usuario @SoyIagoX009.

**Comment by mariosixtogarcia** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/anxocr8/apuntesBD/issues/1) 🚀👾🤖👽

- A Anxo C. co usuario @anxocr8 .
- Por Mario S. co usuario @mariosixtogarcia .

**Comment by ghost** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/razielium7/SQL-DQL/issues/1) 🚀👾🤖👽

- A Vladimir K co usuario @razielium7 .
- Por Juan S. co usuario @juanseijo .

**Comment by ElyOrodas** [comment]
[Revisión apuntamentos SQL DQL 17 de febreiro de 2020 ](https://github.com/nekaneAmeijeiras/Apuntes-SQL/issues/1
)
- A <Nekane-Ameijeiras-Rodríguez> con usuario <@nekaneAmeijeiras>
- Por <Elizabet-Ortiz-Rodas> con usuario <@ElyOrodas>

**Comment by Angelcastrorey** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/AdrianMeru/SQL/issues/1#issue-566130950>) 🚀👾🤖👽
- A Adrián I. co usuario <@AdrianMeru>.
- Por Ángel C. co usuario <@Angelcastrorey>.

**Comment by Eduramirez97** [comment]
👽🤖👾🚀Ligazón a **revisión** apuntamentos **SQL DQL** 17 de Febrero de 2020 (https://github.com/Angelcastrorey/ApuntesSQL-AngelCastro-ASI1)🚀👾🤖👽

· a Ángel C. co usuario @Angelcastrorey 
· Por Eduardo R. co usuario @Eduramirez97

**Comment by Sergio-Iglesias** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/AdolfoGarcia10/Apuntes-SQL-/issues/1) 🚀👾🤖👽

- A Adolfo G. co usuario @AdolfoGarcia10.
- Por Sergio I. co usuario @Sergio-Iglesias.

**Comment by Eduramirez97** [comment]
👽🤖👾🚀[Ligazón a **revisión** apuntamentos **SQL DQL** 17 de Febrero de 2020](https://github.com/Angelcastrorey/ApuntesSQL-AngelCastro-ASI1/issues/1)🚀👾🤖👽

· a Ángel C. co usuario @Angelcastrorey
· Por Eduardo R. co usuario @Eduramirez97

**Comment by IgnacioNuevo** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/adrimerino/Apuntes-SQL-DQL/issues/1) 🚀👾🤖👽

-A Adrián M. co usuario @adrimerino 
-Por Ignacio N. co usuario @IgnacioNuevo

**Comment by TheRoXaS29** [comment]
🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/rubenorona/SQL/issues/1#issue-566138880>) 🚀👾🤖👽

- A Rubén O. co usuario @rubenorona
- Por Diego V. co usuario @TheRoXaS29

**Comment by alexbs01** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/rubenorona/SQL/issues/2#issue-566140173) 🚀👾🤖👽

- A Rubén O. co usuario @rubenorona.
- Por Alejandro B. co usuario @alexbs01.

**Comment by AdrianMeru** [comment]
[ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/pmareque/Apuntes-BD/issues/2#issue-566141211>)
- A Paloma M co usuario @pmareque
- Por Adrián I co usuario @adrianmeru

**Comment by leavdro** [comment]
[**revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/Albertoov92/MySQL/issues/1)

- A AlbertoO co usuario <@Albertoov92>.
- Por LeandroG co usuario <@Lean-1>.

**Comment by manuelvazcas** [comment]
👽🤖👾🚀[ ligazón á revisión apuntamentos SQL DQL 17 de febreiro de 2020](https://github.com/ElyOrodas/Apuntes-MySQL/issues/1) 🚀👾🤖👽
A Elizabet O. co usuario <@ElyOrodas>
Por Manuel V. co usuario <@manuelvazcas>

**Comment by rubenorona** [comment]
👽🤖👾🚀 [ligazón á revisión apuntamentos SQL DQL 17 de febreiro de 2020](https://github.com/Sergio-Iglesias/SQL/issues/1) 🚀👾🤖👽

A Sergio I. co usuario @Sergio-Iglesias
Por Rubén O. co usuario @rubenorona.

**Comment by razielium7** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/patri30suarez/Apuntes/issues/1#issue-566157145>) 🚀👾🤖👽
- A Patricia S. co usuario @patri30suarez
- Por Vladimir K.  co usuario @razielium7

**Comment by yasminlema** [comment]
[ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/AdrianMeru/SQL/issues/2)

- A Adrián I. co usuario @AdrianMeru 

- Por Yasmin L. co usuario @yasminlema

**Comment by Albertoov92** [comment]
[ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/Jul10-S/first-steps-with-git-and-github-wirtz-asir1-and-dam1/issues/1)
- A Julio S co usuario @Jul10-S.
- Por Alberto O co usuario @Albertoov92.

**Comment by inhigovarela** [comment]
[👽🤖👾🚀 ligazón á revisión apuntamentos SQL DQL 17 de febreiro de 2020 🚀👾🤖👽](https://github.com/IgnacioNuevo/SQLBD/issues/1) 
A Ignacio N. co usuario @IgnacioNuevo 
por Iñigo V. co usuario @inhigovarela

**Comment by ghost** [comment]
👽🤖👾🚀 Lamentablemente no puedo corregir los apuntes ya que no los tiene, así que será un 0 🚀👾🤖👽

- A Ceo R. co usuario @nubevoladorakinto .
- Por Juan S. co usuario @juanseijo .

**Comment by leavdro** [comment]
[ligazón á **revisión** apuntamentos **SQL DQL**](https://github.com/mariosixtogarcia/BD_SQL/issues/1)

- A MarioS co usuario @mariosixtogarcia
- Por LeandroG co usuario @Lean-1.

**Comment by pmareque** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/SoyIagoX009/ApuntesSQL/issues/1) 🚀👾🤖👽

- A Iago C co usuario @SoyIagoX009 .
- Por Paloma M co usuario @pmareque

**Comment by manuelvazcas** [comment]
[👽🤖👾🚀 ligazón á revisión apuntamentos SQL DQL 17 de febreiro de 2020 🚀👾🤖👽](https://github.com/Lean-1/ApuntesSQL/issues/1)
- A Leandro G. co usuario @Lean-1 
- Por Manuel V. co usuario @manuelvazcas

**Comment by mariosixtogarcia** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/manuelvazcas/Apuntes-Bases-de-Datos-ASIR1/issues/1) 🚀👾🤖👽

- A Manuel V. co usuario @manuelvazcas .
- Por Mario S. co usuario @mariosixtogarcia .

**Comment by xRase123** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/yasminlema/apuntes-SQL/issues/1) 🚀👾🤖👽

- Por Javier Campos co usuario @xRase123.
- A Yasmin Lema co usuario @yasminlema.
