### ISSUE TITLE
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/ToniChoren/BasesDeDatos/issues/2#issue-566254630) 🚀👾🤖👽

### ISSUE THREAD

**Issue by dam108** [davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1#11]
- A Tony C. co usuario <@ToniChoren>.
- Por <Jose D,> co usuario <@dam108>.

**Comment by davidgchaves** [comment]
@dam108. Tes que contestar a [Issue principal](https://github.com/davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1/issues/2)
