### ISSUE TITLE
Revisión apuntamentos SQL DQL 17 de febreiro de 2020 DAM

### ISSUE THREAD

**Issue by Toresp** [davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1#12]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/naate20/Apuntes-Bases-de-Datos) 🚀👾🤖👽

- A Natalia R co usuario <@naate20>.
- Por Miguel S co usuario <@Toresp>.

**Comment by davidgchaves** [comment]
@Toresp. Tes que contestar a [Issue principal](https://github.com/davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1/issues/2)
