### ISSUE TITLE
Entrega tarefas 1 e 2 (NOVO PLAZO: 14 de abril) ASIR

### ISSUE THREAD

**Issue by davidgchaves** [davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1#15]
[Gist con instruccións entregas 14 de abril](https://gist.github.com/davidgchaves/ed2570382f7681e492d78eb29428d7a7)

Formato **esixido**. Para a **tarefa 2 escollede** o que mellor se axuste ao que fixéchedes.

```
<nome-alumno-e-primeira-letra-do-apelido> co usuario <@usuario-de-github>.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<url-repositorio>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](<url-repositorio>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **gist** instalación **MySQL ou MariaDB** 3 de abril de 2020](<url-gist>) 🚀👾🤖👽
```

**Comment by AdrianMeru** [comment]
👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<https://github.com/AdrianMeru/SQL>) 🚀👾🤖👽
👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](<https://github.com/AdrianMeru/SQL>) 🚀👾🤖👽

**Comment by adrimerino** [comment]
<Adrián M.> co usuario <@adrimerino>.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<https://github.com/adrimerino/Apuntes-SQL>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](<https://github.com/adrimerino/Apuntes-SQL>) 🚀👾🤖👽

**Comment by IgnacioNuevo** [comment]
<IgnacioN> co usuario <@IgnacioNuevo>.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<https://github.com/IgnacioNuevo/SQLBD>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](<https://github.com/IgnacioNuevo/SQLBD>) 🚀👾🤖👽

**Comment by Albertoov92** [comment]
AlbertoO co usuario @Albertoov92. 

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/Albertoov92/MySQL) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [[ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020]](https://github.com/Albertoov92/MySQL/blob/master/MARIADB.PNG) 🚀👾🤖👽

**Comment by mariosixtogarcia** [comment]
MarioS co usuario @mariosixtogarcia.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/mariosixtogarcia/BD_DDL_DML) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/mariosixtogarcia/BD_DDL_DML) 🚀👾🤖👽

**Comment by juliospau** [comment]
Julio S. co usuario @Jul10-S

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/Jul10-S/apuntes-git-github-sql/tree/master/bd-notes) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MariaDB: [ligazón ao **repositorio** de instalación **MariaDB** 3 de abril de 2020](https://github.com/Jul10-S/apuntes-git-github-sql/blob/master/bd-notes/MariaDB.md) 🚀👾🤖👽

**Comment by razielium7** [comment]
Vladimir K. co usuario @razielium7

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/razielium7/SQL-DML-notes) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **gist** instalación **MySQL ou MariaDB** 3 de abril de 2020](https://gist.github.com/razielium7/4ac34d16faac015f7880c64758db983e) 🚀👾🤖👽

**Comment by yasminlema** [comment]
Yasmin L. co usuario <@yasminlema>

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/yasminlema/apuntes-SQL/blob/master/README.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/yasminlema/apuntes-SQL/blob/master/README.md#Instalacion-de-MySQL) 🚀👾🤖👽

**Comment by Angelcastrorey** [comment]
Ángel Castro co usuario <@Angelcastrorey>.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<https://github.com/Angelcastrorey/apuntes-BD>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](<https://github.com/Angelcastrorey/apuntes-BD>) 🚀👾🤖👽

**Comment by ghost** [comment]
Juan Seijo González co usuario  @juanseijo .

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/juanseijo/sql-dql) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/juanseijo/sql-dql) 🚀👾🤖👽

**Comment by leavdro** [comment]
LeandroG co usuario @Lean-1:
>
👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/Lean-1/ApuntesSQL/blob/master/ApuntesSQL_ABRIL-LeandroGalliano%7Easi109.md) 🚀👾🤖👽
>
👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **gist** instalación **MySQL ou MariaDB** 3 de abril de 2020](https://gist.github.com/Lean-1/b66fb2684accf8efaa8d8c3f3ae4660b) 🚀👾🤖👽

**Comment by alexbs01** [comment]
AlejandroB co usuario @alexbs01.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<https://github.com/alexbs01/SQL/blob/master/README.md>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](<https://github.com/alexbs01/SQL/blob/master/README.md>) 🚀👾🤖👽 **(La instalación está al final del README)**

**Comment by rubenorona** [comment]
RubénO co usuario @rubenorona.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/rubenorona/SQL#%C3%ADndice) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/rubenorona/SQL/blob/master/instalacionMariaDB.md) 🚀👾🤖👽

**Comment by nekaneAmeijeiras** [comment]
NekaneA co usuario <@nekaneAmeijeiras>.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<https://github.com/nekaneAmeijeiras/Apuntes-SQL>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](<https://github.com/nekaneAmeijeiras/Apuntes-SQL>) 🚀👾🤖👽

**Comment by AdolfoGarcia10** [comment]
AdolfoG co usuario <@AdolfoGarcia10>.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<https://github.com/AdolfoGarcia10/Apuntes-SQL->) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](<https://github.com/AdolfoGarcia10/Apuntes-SQL->) 🚀👾🤖👽

**Comment by Sergio-Iglesias** [comment]
SergioI co usuario @Sergio-Iglesias.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<https://github.com/Sergio-Iglesias/DDL-DML>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](<https://github.com/Sergio-Iglesias/DDL-DML>) 🚀👾🤖👽

**Comment by ElyOrodas** [comment]
Elizabet Ortiz Rodas con usuario @ElyOrodas
👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/ElyOrodas/Apuntes-MySQL/blob/master/apuntes2.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/ElyOrodas/Apuntes-MySQL/blob/master/apuntes2.md) 🚀👾🤖👽

**Comment by SoyIago** [comment]
Iago C. co usuario @SoyIagoX009

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/SoyIagoX009/Apuntes-SQL/tree/ApuntamentosDDLeDML) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/SoyIagoX009/Apuntes-SQL/tree/ApuntamentosDDLeDML) 🚀👾🤖👽

**Comment by Neragorn** [comment]
Moisés B co usuario @Neragorn
👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL : [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/Neragorn/SQL_DDL_DML/blob/master/DDL.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 1 - Apuntamentos DML : [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/Neragorn/SQL_DDL_DML/blob/master/DML.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/Neragorn/SQL_DDL_DML/blob/master/MariaDB.md) 🚀👾🤖👽

**Comment by davidgchaves** [comment]
Time's up 🥁⏰🕰

**Comment by xRase123** [comment]
<Javier C> co usuario <@xRase123>.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<https://github.com/xRase123/DDL-DML.md>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](<url-repositorio>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **gist** instalación **MySQL ou MariaDB** 3 de abril de 2020](<url-gist>) 🚀👾🤖👽

**Comment by davidgchaves** [comment]
Issue reaberta ata o 14 de abril as 14:00

**Comment by pmareque** [comment]
Paloma M co usuario @pmareque .

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/pmareque/BD-SQL) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/pmareque/BD-SQL) 🚀👾🤖👽

**Comment by manuelvazcas** [comment]
Manuel V co usuario @manuelvazcas
👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML:  [ligazón ao repositorio de apuntamentos SQL DDL e DML 3 de abril de 2020](https://github.com/manuelvazcas/SQL-ASIR1) 🚀👾🤖👽
👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao repositorio de instalación MySQL ou MariaDB 3 de abril de 2020](https://github.com/manuelvazcas/SQL-ASIR1/blob/master/MariaDB.md) 🚀👾🤖👽

**Comment by SoyIago** [comment]
Iago C. co usuario @SoyIagoX009.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 14 de abril de 2020](https://github.com/SoyIagoX009/Apuntes-SQL/tree/ApuntamentosDDLeDMLv2#t2---201920) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 14 de abril de 2020](https://github.com/SoyIagoX009/Apuntes-SQL/tree/ApuntamentosDDLeDMLv2#t3---201920) 🚀👾🤖👽

**Comment by Lean-1** [comment]
Leandro G. co usuario <@Lean-1>.

👽🤖👾🚀 Tarefa 3 - Crear as 2 BBDD dos exercicios que estivemos a resolver antes da cuarentena: [ligazón ao **repositorio** da tarefa do 14 de abril de 2020](https://github.com/Lean-1/ApuntesSQL/blob/master/tarefa3/tarea3-LeandroGalliano%7Easi109.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Comandos de MySQL/MariaDB que permiten ver a estrutura e datos dunha BD simulando unha GUI na ventana de comandos: [ligazón ao **repositorio** da tarefa 4 do 14 de abril de 2020](https://github.com/Lean-1/ApuntesSQL/blob/master/tarea4-Meta_uso_MySQL_o_MariaDB.md) 🚀👾🤖👽
