### ISSUE TITLE
Entrega tarefas 1 e 2 (NOVO PLAZO: 14 de abril) DAM

### ISSUE THREAD

**Issue by davidgchaves** [davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1#16]
[Gist con instruccións entregas 14 de abril](https://gist.github.com/davidgchaves/ed2570382f7681e492d78eb29428d7a7)

Formato **esixido**. Para a **tarefa 2 escollede** o que mellor se axuste ao que fixéchedes.

```
<nome-alumno-e-primeira-letra-do-apelido> co usuario <@usuario-de-github>.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<url-repositorio>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](<url-repositorio>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **gist** instalación **MySQL ou MariaDB** 3 de abril de 2020](<url-gist>) 🚀👾🤖👽
```

**Comment by alexoterof** [comment]
Alex O. có usuario @alexoterof.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/alexoterof/SQL-notes) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **gist** instalación **MySQL ou MariaDB** 3 de abril de 2020](https://gist.github.com/alexoterof/6c89485485752bc05673702f519488e6) 🚀👾🤖👽

**Comment by GabyDev12** [comment]
Gabriel C. co usuario <@MrDev-12>.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<https://github.com/MrDev-12/Apuntes-SublenguajesSQL_BD>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **gist** instalación **MySQL ou MariaDB** 3 de abril de 2020](<https://gist.github.com/MrDev-12/d35c5933d42d71be86e5767c4cd9b031>) 🚀👾🤖👽

**Comment by Toresp** [comment]
Miguel S. co usuario <@Toresp>.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/Toresp/Apuntes-Bases-de-Datos/blob/master/Apuntes_2%C2%BAExamen.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/Toresp/Apuntes-Bases-de-Datos/blob/master/Apuntes_2%C2%BAExamen.md#4) 🚀👾🤖👽

**Comment by naate20** [comment]
<Lucas R. > co usuario <@naate20>.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<https://github.com/naate20/ApuntesBases2>) 🚀👾🤖👽

**Comment by IvanEsparzaVillaverde** [comment]
Iván E. co usuario @IvanEsparzaVillaverde.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/IvanEsparzaVillaverde/Apuntes-2/blob/master/README.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **gist** instalación **MySQL ou MariaDB** 3 de abril de 2020](https://gist.github.com/IvanEsparzaVillaverde/498d74498de71a4e7222e8060c00b16d#file-instalacion-mariadb-md) 🚀👾🤖👽

**Comment by MercedesRegueiro** [comment]
Mercedes R. co usuario @MercedesRegueiro.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/MercedesRegueiro/SQL_SegundosApuntes) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/MercedesRegueiro/SQL_SegundosApuntes/tree/master/8_InstalacionXSBD) 🚀👾🤖👽

**Comment by Fonsi13** [comment]
Luis Alfonso N. co usuario @Fonsi13.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/Fonsi13/Sublenguajes-SQL) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **gist** instalación **MySQL ou MariaDB** 3 de abril de 2020](https://gist.github.com/Fonsi13/35bac821c1cc4f7748e89f84605667d6) 🚀👾🤖👽

**Comment by JrFerraz** [comment]
👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<https://github.com/JrFerraz/BasesDatos2-Apuntes/blob/master/ApuntesFinales.MD>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](<https://github.com/JrFerraz/BasesDatos2-Apuntes/blob/master/MariaDBInstall.MD>) 🚀👾🤖👽

**Comment by dam213** [comment]
Xián-G co usuario @xiaparga.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/xiaparga/SQL/tree/master/2ª-parte) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **gist** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://gist.github.com/xiaparga/bdf6117f49d3c89e957a7f9ececc6bb6) 🚀👾🤖👽

**Comment by ToniChoren** [comment]
ToniCh  co usuario @ToniChoren


> 👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/ToniChoren/BasesDeDatos) 🚀👾🤖👽
> 
> 👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/ToniChoren/BasesDeDatos) 🚀👾🤖👽
> ```

**Comment by DipasDam107** [comment]
Daniel DP. co usuario  @DipasDam107

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/DipasDam107/Base-de-Datos-Relacionales---SQL) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/DipasDam107/Base-de-Datos-Relacionales---SQL/tree/master/mysql) 🚀👾🤖👽

**Comment by iriagonzalez25** [comment]
Iria G. co usuario @iriagonzalez25

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/iriagonzalez25/Bases-de-datos-2/blob/master/Apuntes%20SQL%202.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/iriagonzalez25/Bases-de-datos-2/blob/master/Instalación%20MySQL.MD) 🚀👾🤖👽

**Comment by dam108** [comment]
<Jose D.> co usuario <@dam108>.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/dam108/ApuntesSQL/blob/master/Apuntes/Apuntes_SQL_Segunda_parte.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/dam108/ApuntesSQL/blob/master/EjerciciosSQL/InstalacionGestorMariaDB.md) 🚀👾🤖👽

**Comment by valenmb** [comment]
Valentín M. co usuario @valenmb.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/valenmb/SQL-Apuntes-BD-DAM1/blob/master/sqlddldml.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/valenmb/SQL-Apuntes-BD-DAM1/blob/master/mysql.md) 🚀👾🤖👽

**Comment by AlbertoMartinezPose** [comment]
Alberto M. co usuario @AlbertoMartinezPose .

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/AlbertoMartinezPose/Apuntes-base-de-datos_2-dql-dml) 🚀👾🤖👽
👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **gist** instalación **MySQL ou MariaDB** 3 de abril de 2020](https://gist.github.com/AlbertoMartinezPose/94a9e82e9ddc36664b9793891ad31d12) 🚀👾🤖👽

**Comment by rubeneso** [comment]
Rubén A. co usuario @rubeneso.
 
👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/rubeneso/ApuntesSQL) 🚀👾🤖👽
 
👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/rubeneso/ApuntesSQL) 🚀👾🤖👽

**Comment by mateolopezsoto** [comment]
Mateo López con el usuario @mateolopezsoto
👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<https://github.com/mateolopezsoto/Apuntes-SQL-2>) 🚀👾🤖👽
👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](<https://gist.github.com/mateolopezsoto/6c0815052e70b449623f07eef56b8c1f>) 🚀👾🤖👽

**Comment by davidgchaves** [comment]
Time's up 🥁⏰🕰

**Comment by vendoleiras** [comment]
Iago G.  co usuario @vendoleiras

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/vendoleiras/ApuntesBases2) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/vendoleiras/MySQL) 🚀👾🤖👽


Permiso de @davidgchaves de entregalo despois de haberse pechado a issue

**Comment by Godot99** [comment]
Óscar H. co usuario @Godot99.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](https://github.com/Godot99/DAM1-Bases-de-Datos) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](https://github.com/Godot99/Instalacion-MariaDB) 🚀👾🤖👽

**Comment by davidgchaves** [comment]
Issue reaberta ata o 14 de abril as 14:00

**Comment by LucasDevOs97** [comment]
Lucas R. co usuario <@naate20>.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<https://github.com/naate20/ApuntesBases2>) 🚀👾🤖👽

**Comment by christiancf9** [comment]
Christian C. co usuario @christiancf9

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 14 de abril de 2020](https://github.com/christiancf9/ApuntesSQL) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **gist** instalación **MySQL ou MariaDB** 14 de abril de 2020](https://gist.github.com/christiancf9/2d4452556ae7fbd1514f65af6360619b) 🚀👾🤖👽

**Comment by emiliofds1** [comment]
Emilio.F co usuario <@emiliofds1>.

👽🤖👾🚀 Tarefa 1 - Apuntamentos DDL e DML: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** 3 de abril de 2020](<https://github.com/emiliofds1/Apuntes-SQL/blob/master/SUBLENGUAJES.md>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 2 - Instalación MySQL ou MariaDB: [ligazón ao **repositorio** de instalación **MySQL ou MariaDB** 3 de abril de 2020](<https://github.com/emiliofds1/Apuntes-SQL/blob/master/instalacion%20MySQL.md>) 🚀👾🤖👽
