### ISSUE TITLE
Entrega tarefas 3 e 4 (27 de abril) DAM 

### ISSUE THREAD

**Issue by davidgchaves** [davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1#17]
[Gist con instruccións entregas 27 de abril](https://gist.github.com/davidgchaves/43c9e8d786b30259ca64dfcb26df1547)

Formato **esixido**.

```
<nome-alumno-e-primeira-letra-do-apelido> co usuario <@usuario-de-github>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<url-repositorio>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<url-repositorio>) 🚀👾🤖👽
```

**Comment by dam213** [comment]
Xián-G co usuario @xiaparga

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/xiaparga/SQL/tree/Tareas3y4) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/xiaparga/SQL/tree/Tareas3y4) 🚀👾🤖👽

**Comment by GabyDev12** [comment]
Gabriel C. co usuario <@MrDev-12>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/MrDev-12/Apuntes-SublenguajesSQL_BD/tree/tarefa3>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/MrDev-12/Apuntes-SublenguajesSQL_BD/tree/tarefa4>) 🚀👾🤖👽

**Comment by JrFerraz** [comment]
<Jorge-F> co usuario <@JrFerraz>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/JrFerraz/BasesDatos2-Apuntes/releases/tag/tarefa3>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/JrFerraz/BasesDatos2-Apuntes/releases/tag/tarefa4>) 🚀👾🤖👽

**Comment by dam108** [comment]
Jose Angel D. co usuario <@dam108>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/dam108/ApuntesSQL/releases/tag/CreacionBasesDeDatos>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/dam108/ApuntesSQL/releases/tag/ComandosBasicosMariaDB>) 🚀👾🤖👽

**Comment by ToniChoren** [comment]
ToniCh  con usuario @ToniChoren

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/ToniChoren/BasesDeDatos/releases/tag/creacionBasesDatos>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/ToniChoren/BasesDeDatos/releases/tag/probarComandos>) 🚀👾🤖👽

**Comment by DipasDam107** [comment]
Daniel DP. co usuario <@DipasDam107>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/DipasDam107/Base-de-Datos-Relacionales---SQL/releases/tag/tarefa3) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/DipasDam107/Base-de-Datos-Relacionales---SQL/releases/tag/tarefa4) 🚀👾🤖👽

**Comment by iriagonzalez25** [comment]
Iria G. co usuario @iriagonzalez25

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/iriagonzalez25/Bases-de-datos-2/releases/tag/tarefa3) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/iriagonzalez25/Bases-de-datos-2/releases/tag/tarefa4) 🚀👾🤖👽

**Comment by rubeneso** [comment]
Rubén A. co usuario @rubeneso.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/rubeneso/ApuntesSQL/releases/tag/tarefa3) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/rubeneso/ApuntesSQL/releases/tag/tarefa4) 🚀👾🤖👽

**Comment by Toresp** [comment]
Miguel S. co usuario <@Toresp>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/Toresp/Apuntes-Bases-de-Datos/releases/tag/Tarefa3e4>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/Toresp/Apuntes-Bases-de-Datos/releases/tag/Tarefa3e4>) 🚀👾🤖👽

**Comment by Fonsi13** [comment]
Luis Alfonso N. co usuario @Fonsi13.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/Fonsi13/Sublenguajes-SQL) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/Fonsi13/Sublenguajes-SQL) 🚀👾🤖👽

**Comment by MercedesRegueiro** [comment]
Mercedes Regueiro co usuario @MercedesRegueiro.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/MercedesRegueiro/CreacionBasesDeDatos) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/MercedesRegueiro/CreacionBasesDeDatos/tree/master/3_Comandos) 🚀👾🤖👽

**Comment by alexoterof** [comment]
Alex Otero co usuario @alexoterof

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/alexoterof/SQL-notes/releases/tag/Exercicio3) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/alexoterof/SQL-notes/releases/tag/Exercicio4) 🚀👾🤖👽

**Comment by angelronoya** [comment]
Angel R.  co usuario <@angelronoya>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/angelronoya/Ejercicios-Proyecto-de-Investigacion-y-Naves-Espaciales-/releases/tag/tarefa3>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/angelronoya/Ejercicios-Proyecto-de-Investigacion-y-Naves-Espaciales-/releases/tag/tarefa4>) 🚀👾🤖👽

Sintoo, non me acordei de subir as tarefas 1 e 2 como xa che comentei, pero deixoas por aquí igualmente. Teño as tarefas 1 e 2 no mesmo repositorio.

Tarefas 1 e 2 - Apuntamentos **SQL DDL e DML** e instalación de MySQL en Windows: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/angelronoya/Apuntes-Parte-2-SQL-Angel-Rodriguez>)

**Comment by AlbertoMartinezPose** [comment]
Alberto M. co usuario @AlbertoMartinezPose.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/AlbertoMartinezPose/tarea-3-bases/blob/master/README.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/AlbertoMartinezPose/tarea-3-bases/blob/master/README.md) 🚀👾🤖👽

**Comment by IvanEsparzaVillaverde** [comment]
Iván E.  co usuario @IvanEsparzaVillaverde.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/IvanEsparzaVillaverde/Apuntes-2/blob/master/Exercicios.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/IvanEsparzaVillaverde/Apuntes-2/blob/master/Exercicios.md) 🚀👾🤖👽

**Comment by emiliofds1** [comment]
Emilio F. co usuario @emiliofds1.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/emiliofds1/B.D-Tarea3-4/releases/tag/Tarea3>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/emiliofds1/B.D-Tarea3-4/releases/tag/Tarea3>) 🚀👾🤖👽

**Comment by christiancf9** [comment]
Christian C. co usuario @christiancf9.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao [tag concreto (**MOITO MELLOR**)](https://github.com/christiancf9/ApuntesSQL/releases/tag/Tarefa3) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao [tag concreto (**MOITO MELLOR**)](https://github.com/christiancf9/ApuntesSQL/releases/tag/Tarefa4) 🚀👾🤖👽

**Comment by adrianbaldonedo** [comment]
Adrian-B co usuario @adriabaldonedo.
👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/adrianbaldonedo/CreacionBaseDatos) 🚀👾🤖👽
👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/adrianbaldonedo/CreacionBaseDatos) 🚀👾🤖👽

**Comment by mateolopezsoto** [comment]
<Mateo L> co usuario <@mateolopezsoto>.

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://gist.github.com/mateolopezsoto/3ed92ddc38584c3264d1b1c66ae9f743>) 🚀👾🤖👽

**Comment by valenmb** [comment]
Valentín M. co usuario @valenmb.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/valenmb/SQL-Apuntes-BD-DAM1) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/valenmb/SQL-Apuntes-BD-DAM1) 🚀👾🤖👽

**Comment by vendoleiras** [comment]
Iago G. co usuario @vendoleiras.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/vendoleiras/ExerciciosMySQL/releases/tag/tarefa3) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/vendoleiras/ExerciciosMySQL/releases/tag/tarefa4) 🚀👾🤖👽

**Comment by davidgchaves** [comment]
Time's up 🥁⏰🕰

**Comment by Godot99** [comment]
Óscar H. co usuario @Godot99.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/Godot99/DAM1-Bases-de-Datos/tree/master/Ejercicios%203%20y%204) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/Godot99/DAM1-Bases-de-Datos/tree/master/Ejercicios%203%20y%204) 🚀👾🤖👽

**Comment by LucasDevOs97** [comment]
<Lucas R.> co usuario <@naate20>.

Ampliado prazo de entrega tras falar co profesor.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/naate20/ApuntesBases2/tree/master/Ejercicios_DDL>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/naate20/ApuntesBases2/tree/master/Ejercicios_DDL>) 🚀👾🤖👽
