### ISSUE TITLE
Entrega tarefas 3 e 4 (27 de abril) ASIR

### ISSUE THREAD

**Issue by davidgchaves** [davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1#18]
[Gist con instruccións entregas 27 de abril](https://gist.github.com/davidgchaves/43c9e8d786b30259ca64dfcb26df1547)

Formato **esixido**.

```
<nome-alumno-e-primeira-letra-do-apelido> co usuario <@usuario-de-github>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<url-repositorio>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<url-repositorio>) 🚀👾🤖👽
```

**Comment by adrimerino** [comment]
<Adrian M> co usuario <@adrimerino>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/adrimerino/Apuntes-SQL>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/adrimerino/Apuntes-SQL>) 🚀👾🤖👽

**Comment by juliospau** [comment]
Julio S. co usuario <@Jul10-S>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MariaDB`: [ligazón ao tag](<https://github.com/Jul10-S/apuntes-git-github-sql/releases/tag/tarefa3>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao tag](<https://github.com/Jul10-S/apuntes-git-github-sql/releases/tag/tarefa4>) 🚀👾🤖👽

**Comment by rubenorona** [comment]
RubenO co usuario @rubenorona

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MariaDB`: [ligazón ao **repositorio** do exemplo1](https://github.com/rubenorona/SQL/blob/master/exemplo1_MariaDB.md), [ligazón ao **repositorio** do exemplo 2](https://github.com/rubenorona/SQL/blob/master/exemplo2_MariaDB.md) e [ligazón ao **tag** concreto](https://github.com/rubenorona/SQL/releases/tag/tarefa3) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MariaDB`: [ligazón ao **repositorio**](https://github.com/rubenorona/SQL/blob/master/metadata_MariaDB.md) e [ligazón ao **tag** concreto](https://github.com/rubenorona/SQL/releases/tag/tarefa4) 🚀👾🤖👽

**Comment by pmareque** [comment]
Paloma M co usuario @pmareque .

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/pmareque/MariaDB-T3-Crear-2-BBDD/releases/tag/tarefa3) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/pmareque/MariaDB-T4-Metauso/releases/tag/tarefa4) 🚀👾🤖👽

**Comment by razielium7** [comment]
Vladimir K. co usuario @razielium7 .

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao tag ](https://github.com/razielium7/MySQL_practice/releases/tag/tarefa3) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao tag ](https://github.com/razielium7/MySQL_practice/releases/tag/tarefa4) 🚀👾🤖👽

**Comment by alexbs01** [comment]
Alejandro B. co usuario @alexbs01.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/alexbs01/SQL/blob/master/ImplementacionConMariaDB.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/alexbs01/SQL/blob/master/ImplementacionConMariaDB.md#Formas-de-ver-la-estructura-de-la-BD) 🚀👾🤖👽

**Comment by ElyOrodas** [comment]
<Elizabet O.> co usuario <@ElyOrodas>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/ElyOrodas/Apuntes-MySQL/blob/master/apuntes3.md>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/ElyOrodas/Apuntes-MySQL/blob/master/apuntes3.md>) 🚀👾🤖👽

**Comment by manuelvazcas** [comment]
Manuel V. co usuario @manuelvazcas

👽🤖👾🚀 Tarefa 3 - [Creación de BBDD en MySQL / MariaDB: ligazón ao repositorio de apuntamentos SQL DDL e DML](https://github.com/manuelvazcas/SQL-ASIR1/blob/master/ImplementacionMariaDB.md)  ou [ao tag concreto (MOITO MELLOR)](https://github.com/manuelvazcas/SQL-ASIR1/blob/TAREA3/ImplementacionMariaDB.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - [Meta uso de MySQL / MariaDB: ligazón ao repositorio de apuntamentos SQL DDL e DML](https://github.com/manuelvazcas/SQL-ASIR1/blob/master/ComandosMariaDB.md) ou [ao tag concreto (MOITO MELLOR)](https://github.com/manuelvazcas/SQL-ASIR1/blob/TAREA4/ComandosMariaDB.md) 🚀👾🤖👽

**Comment by yasminlema** [comment]
Yasmin L. co usuario @yasminlema.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/yasminlema/SQL/releases/tag/v1.0) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/yasminlema/SQL/releases/tag/v1.0) 🚀👾🤖👽

**Comment by mariosixtogarcia** [comment]
<nome-alumno-e-primeira-letra-do-apelido> co usuario <@usuario-de-github>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/mariosixtogarcia/BD_DDL_DML/blob/master/Creacion%20BD.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/mariosixtogarcia/BD_DDL_DML/blob/master/Creacion%20BD.md) 🚀👾🤖👽

**Comment by Albertoov92** [comment]
Alberto O co usuario @Albertoov92

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/Albertoov92/MySQL/blob/master/Creacion%20BD.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/Albertoov92/MySQL/blob/master/Creacion%20BD.md) 🚀👾🤖👽

**Comment by IgnacioNuevo** [comment]
<IgnacioN> co usuario <@IgnacioNuevo>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/IgnacioNuevo/SQLBD/blob/master/MariaDB.md>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/IgnacioNuevo/SQLBD/blob/master/MariaDB.md>) 🚀👾🤖👽

**Comment by AdrianMeru** [comment]
> <Adrian I> co usuario <@AdrianMeru>.
> 
> 👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/AdrianMeru/SQL/blob/master/Creacion%20de%202%20bases%20de%20datos.md) 🚀👾🤖👽
> 
> 👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/AdrianMeru/SQL/blob/master/Visualizar%20una%20base%20de%20datos%20en%20Maria%20DB.md) 🚀👾🤖👽

**Comment by nekaneAmeijeiras** [comment]
Nekane Ameijeiras Rodríguez co usuario <@nekaneAmeijeiras>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/nekaneAmeijeiras/Apuntes-SQL/releases/tag/DDL-v1.0>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/nekaneAmeijeiras/Apuntes-SQL/releases/tag/DDL-v1.0>) 🚀👾🤖👽

**Comment by Neragorn** [comment]
<Moisés B> co usuario <@Neragorn>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/Neragorn/MariaDB/releases/tag/1.0>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/Neragorn/MariaDB/releases/tag/1.1>) 🚀👾🤖👽

**Comment by Sergio-Iglesias** [comment]
Sergio I. co usuario @Sergio-Iglesias.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/Sergio-Iglesias/DDL-DML/releases/tag/tarefa3) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/Sergio-Iglesias/DDL-DML/releases/tag/tarefa4) 🚀👾🤖👽

**Comment by Angelcastrorey** [comment]
<AngelCastro> co usuario <@angelcastrorey>.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/Angelcastrorey/apuntes-BD/blob/master/tarea3.md>) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](<https://github.com/Angelcastrorey/apuntes-BD/blob/master/tarea4.md>) 🚀👾🤖👽

**Comment by leavdro** [comment]
E.Leandro Galliano.G co usuario @Lean-1.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/Lean-1/ApuntesSQL/releases/tag/tarea3) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/Lean-1/ApuntesSQL/releases/tag/tarea4) 🚀👾🤖👽

**Comment by davidgchaves** [comment]
Time's up 🥁⏰🕰

**Comment by ghost** [comment]
Habilitada entrega fuera de plazo por razones previamente justificadas y discutidas con el docente

Juan S. co usuario @juanseijo.

👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/juanseijo/sql-dql/blob/master/MariaDB.md) 🚀👾🤖👽

👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/juanseijo/sql-dql/blob/master/MariaDB.md) 🚀👾🤖👽
