### ISSUE TITLE
Adrian Baldonedo

### ISSUE THREAD

**Issue by adrianbaldonedo** [davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1#19]
Adrian-B co usuario @adriabaldonedo.
👽🤖👾🚀 Tarefa 3 - Creación de BBDD en `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/adrianbaldonedo/CreacionBaseDatos) 🚀👾🤖👽
👽🤖👾🚀 Tarefa 4 - Meta uso de `MySQL` / `MariaDB`: [ligazón ao **repositorio** de apuntamentos **SQL DDL e DML** ou ao tag concreto (**MOITO MELLOR**)](https://github.com/adrianbaldonedo/CreacionBaseDatos) 🚀👾🤖👽

**Comment by davidgchaves** [comment]
@adrianbaldonedo, non podes entregar aquí, creando unha nova Issue. Fíxate nos teus compañerios, entregaron engadindo un comentario na Issue creada por min.
