### ISSUE TITLE
Revisión apuntamentos SQL DQL 17 de febreiro de 2020 DAM

### ISSUE THREAD

**Issue by davidgchaves** [davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1#2]
Formato recomendado

```
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<url-revisión>) 🚀👾🤖👽

- A <nome-alumno-e-primeira-letra-do-apelido-revisado> co usuario <@usuario-de-github>.
- Por <nome-alumno-e-primeira-letra-do-apelido-que-revisa> co usuario <@usuario-de-github>.
```

**Comment by giannyuffo** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/Toresp/Apuntes-Bases-de-Datos/issues/1#issue-566250195) 🚀👾🤖👽

- A Miguel S. co usuario @Toresp.
- Por Gianny U. co usuario @giannyuffo.

**Comment by MartinMP00** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/valenmb/SQL-Apuntes-BD-DAM1/issues/1) 🚀👾🤖👽

- A Valentín M. co usuario @valenmb.
- Por Martin M. co usuario @MartinMP00.

**Comment by LucasDevOs97** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/angelronoya/Apuntes-SQL-Angel-Rodriguez/issues/1) 🚀👾🤖👽
- A Ángel R. co usuario @angelronoya
- Por Lucas R. co usuario @naate20

**Comment by adrianbaldonedo** [comment]
[ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/MartinMP00/ApuntesSQL/issues/1#issue-566252390)

- A Martin M co usuario @MartinMP00
- Por Adrián B. con usuario@adrianbaldonedo

**Comment by MercedesRegueiro** [comment]
👽🤖👾🚀[ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/iriagonzalez25/Apuntes-/issues/1)🚀👾🤖👽

- A Iria G. co usuario @iriagonzalez25.
- Por Merchi R. co usuario @MercedesRegueiro.

**Comment by diegorivitas** [comment]
[ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/JrFerraz/BASES-APUNTES-Markdown/issues/1) 🚀👾🤖👽

- A Jorge F. co usuario @JrFerraz
- Por Diego R. co usuario @diegorivitas

**Comment by JrFerraz** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/DavidMateos98/ApuntesBD/issues/1#issue-566254351>) 🚀👾🤖👽
- A <DavidM> co usuario <@DavidMateos98>.
- Por <JorgeF> co usuario <@JrFerraz>.

**Comment by iriagonzalez25** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/Godot99/DAM1-Bases-de-Datos/issues/1) 🚀👾🤖👽

- A Óscar H. co usuario @Godot99.
- Por Iria G. co usuario @iriagonzalez25.

**Comment by alexoterof** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/diegorivitas/APUNTES/issues/1#issue-566256816>) 🚀👾🤖👽
- A Diego R co usuario @diegorivitas 
- Por Alex O co usuario @alexoterof

**Comment by IvanEsparzaVillaverde** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/vendoleiras/ApuntesSQL/issues/1>) 🚀👾🤖👽

- A <Iago G.> co usuario <@vendoleiras>.
- Por <Iván E.> co usuario <@IvanEsparzaVillaverde>.

**Comment by dam108** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/ToniChoren/BasesDeDatos/issues/2#issue-566254630) 🚀👾🤖👽 
 
- A Tony C. co usuario @ToniChoren
- Por Jose D co usuario @dam108

**Comment by IvanEsparzaVillaverde** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/vendoleiras/ApuntesSQL/issues/1) 🚀👾🤖👽

- A Iago G. co usuario @vendoleiras.
- Por Iván E. co usuario @IvanEsparzaVillaverde.

**Comment by christiancf9** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/Fonsi13/first-steps-example/issues/1>) 🚀👾🤖👽

- A LuisN co usuario @fonsi13
- Por ChristianC co usuario @christiancf9

**Comment by vendoleiras** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/MercedesRegueiro/SQL_MisApuntes/issues/1#issue-566259320>) 🚀👾🤖👽

- A MercedesR co usuario <@MercedesRegueiro>.
- Por IagoG co usuario <@vendoleiras>.

**Comment by Godot99** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/adrianbaldonedo/adrian/issues/1) 🚀👾🤖👽

- A Adrián B. co usuario @adrianbaldonedo .
- Por Óscar H. co usuario @Godot99.

**Comment by Toresp** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/naate20/Apuntes-Bases-de-Datos/issues/1) 🚀👾🤖👽

- A Natalia R co usuario <@naate20>.
- Por Miguel S co usuario <@Toresp>.

**Comment by DavidMateos98** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/alexoterof/ApuntesSQL/issues/1) 🚀👾🤖👽

- A Alex O. co usuario <@alexoterof>.
- Por David M. co usuario <@DavidMateos98>.

**Comment by GabyDev12** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/christiancf9/ApuntesSQL/issues/1#issue-566264706>) 🚀👾🤖👽

- A Christian C co usuario <@christiancf9>.
- Por Gabriel C co usuario <@MrDev-12>.

**Comment by rubeneso** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/dam108/ApuntesSQL/issues/2) 🚀👾🤖👽
 
 - A Jose D co usuario <@dam108> .
 - Por Ruben A co usuario <@rubeneso>.

**Comment by ToniChoren** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/DipasDam107/Bases/issues/1) 🚀👾🤖👽

 - A Daniel-D co usuario <@DipasDam107>.
 - Por Toni-Ch  co usuario <@tonichoren>.

**Comment by DipasDam107** [comment]
👽🤖👾🚀 [ligazón á revisión apuntamentos SQL DQL 17 de febreiro de 2020](https://github.com/rubeneso/ApuntesSQL/issues/1#issue-566272378) 🚀👾🤖👽

A Rubén-A co usuario <@rubeneso>.
Por Daniel-D co usuario <@DipasDam107>.

**Comment by Fonsi13** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/xiaparga/Apuntes-de-SQL-1-parte/issues/1#issue-566273120) 🚀👾🤖👽 
- A Xián P. co usuario <@xiaparga>.
- Por Luis No co usuario <@Fonsi13>.

**Comment by valenmb** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/IvanEsparzaVillaverde/apuntes-SQL/issues/1) 🚀👾🤖👽

- A <Iván E> co usuario <@IvanEsparzaVillaverde>.
- Por <Valentín M> co usuario <@valenmb>.

**Comment by dam213** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/MrDev-12/Apuntes-SQL_Bases-de-Datos/issues/1) 🚀👾🤖👽

- A Gabriel-C co usuario @MrDev-12.
- Por Xián-G co usuario @xiaparga.

**Comment by angelronoya** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/giannyuffo/Base-de-Datos.-SQL/issues/1>) 🚀👾🤖👽

- A <Gianny U> co usuario <@giannyuffo>.
- Por <Angel R> co usuario <@angelronoya>.

**Comment by mateolopezsoto** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](https://github.com/emiliofds1/Apuntes-SQL/issues/1#issue-568481707) 🚀👾🤖👽

- A <Emilio F> co usuario <@emiliofds1>.
- Por <Mateo L> co usuario <@mateolopezsoto>.

**Comment by emiliofds1** [comment]
[👽🤖👾🚀 ligazón á revisión apuntamentos SQL DQL 17 de febreiro de 2020 🚀👾🤖👽](https://github.com/AlbertoMartinezPose/Apuntes-SQL/issues/1#issue-568549763)
- A Alberto M. co usuario @AlbertoMartinezPose.
- Por Emilio F. co usuario @Emiliofds1

**Comment by AlbertoMartinezPose** [comment]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/mateolopezsoto/Apuntes-SQL/issues/1#issue-568789540>) 🚀👾🤖👽

- A Mateo L co usuario @mateolopezsoto.
- Por Alberto M co usuario @AlbertoMartinezPose.
