### ISSUE TITLE
Adrian Baldonedo CreacionBaseDatos

### ISSUE THREAD

**Issue by adrianbaldonedo** [davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1#20]
Pasos para crear una base de datos con los ejercicios comentados en clase
Adrian-B co usuario @adriabaldonedo.
👽🤖👾🚀 Tarefa 3 - Creación de BBDD en MySQL / MariaDB: ligazón ao repositorio de apuntamentos SQL DDL e DML ou ao tag concreto (MOITO MELLOR) 🚀👾🤖👽
👽🤖👾🚀 Tarefa 4 - Meta uso de MySQL / MariaDB: ligazón ao repositorio de apuntamentos SQL DDL e DML ou ao tag concreto (MOITO MELLOR) 🚀👾🤖👽

**Comment by davidgchaves** [comment]
Entregaches mal 2 veces
