### ISSUE TITLE
Corrección apuntes SQL 

### ISSUE THREAD

**Issue by AdrianMeru** [davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1#4]
https://github.com/pmareque/Apuntes-BD/issues/2#issue-566141211
- A Paloma M co usuario pmareque
- Por Adrián I co usuario adrianmeru

**Comment by davidgchaves** [comment]
@AdrianMeru , no [fio principal](https://github.com/davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1/issues/1) mellor.

Pon link aos usuarios con `@usuario`.
