### ISSUE TITLE
Corrección Apuntes Iago Casal ASI1

### ISSUE THREAD

**Issue by pmareque** [davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1#7]
👽🤖👾🚀 [ligazón á **revisión** apuntamentos **SQL DQL** 17 de febreiro de 2020](<https://github.com/SoyIagoX009/ApuntesSQL/issues/1>) 🚀👾🤖👽

- A Iago C. co usuario @SoyIagoX009 .
- Por Paloma M. co usuario @pmareque.

**Comment by davidgchaves** [comment]
@pmareque , no [fio principal](https://github.com/davidgchaves/first-steps-with-git-and-github-wirtz-asir1-and-dam1/issues/1) mellor.
